### ISSUE TITLE
Reference pitch and transposition attributes

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda-core#21]
Moved from https://github.com/alda-lang/alda/issues/236.

- `transpose` or `transposition` attribute: when writing music for a Bb clarinet playing in the key of Bb (i.e. reading the part like it's in C), `clarinet: (transpose -2) c8 d e f g a b > c` would produce a Bb major scale.

- `reference-pitch` or `tuning-constant` attribute would specify an alternate pitch of A4, with the default being 440 Hz (A440)

**Comment by snigdhaAgarwal** [comment]
@daveyarwood - I would like to take up this issue if it is still available. Can you help me in getting started? I have never worked in clojure before but would like to learn. 
I have installed boot so far.
Thanks

**Comment by abhi18av** [comment]
Hi @fankee 

You can check out the basic online book/tutorials like [Clojure for the brave and true](http://www.braveclojure.com/clojure-for-the-brave-and-true/)

[Getting to know boot](https://lionfacelemonface.wordpress.com/2015/01/17/boot-getting-started-with-clojure-in-10-minutes/) - please do follow through with the references towards the bottom.

Awesome documentation and reference[clojure-doc](http://clojure-doc.org/) and [clojuredocs](https://clojuredocs.org/)

A handy summary of syntax can be found -> [cheat-cheet for clojure](https://www.conj.io/)

Dev. environments for getting started sort of depends on you, I know that @daveyarwood  prefers *vim* and *cider-ide* based on *emacs* is pretty popular. Of course there's *cursive* based on IntelliJ. But, if you don't have any preference as of now, pick something easy initially  like [Nightcode](https://sekao.net/nightcode/) or [Nightlight](https://sekao.net/nightlight/). 

If you've used Atom before, then [proto-repl](https://github.com/jasongilman/proto-repl)

Hope this helps.

**Comment by abhi18av** [comment]
Oh, and you can of course get acquainted with the code base using [alda-docs](https://github.com/alda-lang/alda/tree/master/doc)

**Comment by daveyarwood** [comment]
@fankee Thanks for offering to help! I'm always happy to help if you run into any technical questions about Clojure or the Alda codebase -- feel free to ping me here or in the [Alda Slack group](http://slack.alda.io/).

@abhi18av linked to some great resources. I can personally vouch for Clojure for the Brave and True -- it was written by a good friend of mine and it's an excellent way to start learning Clojure.

**Comment by daveyarwood** [comment]
Closed via #59. Will deploy a release soon.
