### ISSUE TITLE
One more example to add to the list

### ISSUE THREAD

**Issue by bring2dip** [alda-lang/alda-core#28]
I have written a score for Beethoven's Fur Elise. I wish you could add that to the list of examples. If you want me to send the PR I will do it.

**Comment by elydpg** [comment]
Ooh that raises an interesting point. I have a bunch of scores that I could put in examples. I think we need a score sharing platform to make it easy to find alda scores for specific pieces as well, however that is not as pertinent to your request.

**Comment by bring2dip** [comment]
Well, that sounds amazing for me. I saw the examples folder and the scores were on basic grammar and how to use variables and all.  If we can have a separate repo for the pieces it would be great.

**Comment by daveyarwood** [comment]
I think a community scores repo is a great idea!

The examples folder in this repo is used primarily for testing purposes, so I would agree that a separate repo is a good idea.

**Comment by daveyarwood** [comment]
@bring2dip @elyisgreat I think [/r/alda](https://reddit.com/r/alda) would also be a good place to share scores :)

**Comment by bring2dip** [comment]
@daveyarwood In my viewpoint, a separate repo would be good in this case.It would be organized and searching would also be easier rather than sharing it on Reddit which would mix with other posts.

**Comment by elydpg** [comment]
Actually I was thinking of eventually bringing this issue up on r/alda. I don't think reddit is a great place for widespread file sharing due to the difficulty of searching and, as @bring2dip mentioned, it would have to mix with other posts. 

Posting scores to pastebin, GitHub, or other file sharing sites is nice, however it's hard to search those sites for specifically Alda content.

Personally I think the best option is a standalone website where you can browse "Alda project pages" with links to download the scores. Possibly even as part of alda.io...

**Comment by daveyarwood** [comment]
This all makes sense to me, but it feels like something that should be an unofficial community effort outside of the alda-lang org. I would happily contribute, of course!

**Comment by elydpg** [comment]
Perhaps we could call it alda-scores.io or something of the sort?

Hmm. I'm wondering where exactly this issue belongs...

**Comment by bring2dip** [comment]
Let us make a repo outside of the official alda-lang org "alda-scores" would be a good choice. And somewhere in the alda repo we can add a link for the alda-scores repo.How do you say  @elyisgreat @daveyarwood

**Comment by daveyarwood** [comment]
I'm very much in favor of a score-sharing website like @elyisgreat mentioned, but I'd like to keep the Alda team (myself mostly 😀 ) focused on maintaining Alda itself. So, I'm going to close this issue in light of that.

I think an "unofficial" Alda community scores repo would be a good start, and if someone web-savvy wanted to make a web application for sharing Alda scores, I would fully endorse it and likely contribute! I'd also be happy to include a link in the Alda README and docs.

**Comment by elydpg** [comment]
There's a repo called [alda-scores](https://github.com/command3r/alda-scores), but it looks like it hasn't been touched in awhile. For the web app I think using [wordpress](https://wordpress.org) would be the easiest option (in case future me wanted to take on the task, however I am not that web-savvy.)

**Comment by bring2dip** [comment]
@elyisgreat I have created the repo with the same name [alda-scores](https://github.com/bring2dip/alda-scores) . As the command3r's repo seems to be inactive.  I will create a github page for it.

**Comment by elydpg** [comment]
Nice! I checked out your für elise score. Looks like some of the octave markers are out, causing some notes to be in the wrong octave. It also felt incomplete; it was using one instrument only, when it could benefit from two. However it is very easy to read.

**Comment by bring2dip** [comment]
@elyisgreat yes it's the first time I've written a piece in alda. It is written from easy piano sheet. There are many things to improve. I have added a link of the sheet music you can have a look at it. And please also send your scores.

**Comment by elydpg** [comment]
For your first score, it's quite good (My scores, even the good ones, are not as nicely styled)! btw If you want to continue your Für Elise beyond the sheet you provided, there's a good sheet of the full thing [here](http://www.forelise.com/media/for_elise_sheet_music.pdf).

**Comment by bring2dip** [comment]
@elyisgreat you can send your scores and I can style them for you. I will also look at the full sheet in my spare time and try to cover it full.
