### ISSUE TITLE
Suggestion: new key signature vectors for other modes

### ISSUE THREAD

**Issue by elydpg** [alda-lang/alda-core#36]
Currently, the `key-signature` attribute has an option to set the key signature using a vectored name, such as

`(key-sig [:e :flat :major]) e f g a b > c d e <`

I propose that the `:major` and `:minor` parameters be extended to support more modes, such as `:dorian` and `:phrygian`. 

Should this be native behaviour? Or would a plugin for it make more sense?

**Comment by daveyarwood** [comment]
Great idea! I think this is something we should include in alda-core.
