### ISSUE TITLE
REPL does not check before loading score

### ISSUE THREAD

**Issue by elydpg** [alda-lang/alda-core#39]
Pretty much the title. If a score is loaded in using `:load`, it will not throw an override warning if there is already a score in the REPL.

**Comment by daveyarwood** [comment]
Yep, confirmed!

We should check to see if the score in the REPL has any changes compared to the score on disk, and prompt for confirmation.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-client-java/issues/17.
