### ISSUE TITLE
REPL starts even if the server is down

### ISSUE THREAD

**Issue by elydpg** [alda-lang/alda-core#40]
In 1.0.0rc57, the REPL now requires the server to run, finally uniting the separate interfaces. However, the REPL still opens even if the server is down. Of course, when attempting to do anything without the server, an error is thrown, however it may make more sense to check the server status prior to starting the REPL.

**Comment by daveyarwood** [comment]
I like this idea. I think maybe what we should do is check to see if the server is up, and if it isn't, ask if you want to start the server, and start it for you.

**Comment by daveyarwood** [comment]
Moved to https://github.com/alda-lang/alda-client-java/issues/18
