### ISSUE TITLE
Ties not working?

### ISSUE THREAD

**Issue by NonlinearFruit** [alda-lang/alda-core#46]
[Disclaimer: I'm a programmer, not a musician]

I am trying to transcribe the lyric notes from the song *'Happy'*.  But the sideways-parenthesis/tie/tilde isn't combining the notes like I think it should. It is very possible that I have mixed up the notation.

Here is my attempt:
```
piano:
  r4 r8 c8 f8 f8~f8 f8~f8 c8 c8 c8 e-8 e-8 f4
```

Here is the music notation version:
![image](https://user-images.githubusercontent.com/6962125/27979122-a405f032-6341-11e7-81f9-db56457a5496.png)

**Comment by aengelberg** [comment]
I believe the ties should be `f8~8`, not `f8~f8`.

**Comment by NonlinearFruit** [comment]
That works! Thanks!
