### ISSUE TITLE
Human voices

### ISSUE THREAD

**Issue by MinaBombo** [alda-lang/alda-core#48]
Should we give it a try? Maybe some humming?

**Comment by elydpg** [comment]
Currently alda only supports MIDI instruments. There are some MIDI voices, however this feature request would fall under support of non MIDI instruments (see [here](https://github.com/alda-lang/alda/issues/287) for more info)

**Comment by daveyarwood** [comment]
An idea I had was to add a "sampler" instrument that can load a sample (e.g. a .wav file) and play melodies/chords by adjusting the speed and pitch of the sample.

**Comment by MinaBombo** [comment]
And is there any ongoing plans regarding it?

**Comment by daveyarwood** [comment]
No development has happened yet -- it's just been an idea in my head for a long while that I haven't had the opportunity to implement yet.

I opened https://github.com/alda-lang/alda-sound-engine-clj/issues/9 just now to track the feature idea. It's definitely something I want to do, but it will probably be quite a while before I can get to it. Contributions are very welcome, if someone wants to take a stab at it!

**Comment by MinaBombo** [comment]
Sounds like a plan!
