### ISSUE TITLE
use changemap.co for a community TODO

### ISSUE THREAD

**Issue by 0atman** [alda-lang/alda-core#49]
http://changemap.co allows more interaction with your users in planning and commenting on the roadmap:
![screenshot-changemap co-2017-09-12-13-41-52](https://user-images.githubusercontent.com/114097/30326329-264c99da-97c0-11e7-8d1f-667cb91c2cc2.png)

I think we should use it, and I'd be happy to set it up!

**Comment by 0atman** [comment]
What do you think @daveyarwood ?

**Comment by daveyarwood** [comment]
@0atman Thanks for the suggestion. changelog.co looks interesting and is compelling, but I think at this point, the Alda project is small enough that I'm happy with managing feature requests and the roadmap via GitHub issues and [our waffle.io board](https://waffle.io/alda-lang/alda).

It's good to know about changelog.co, though. I think at some point in the future, when Alda grows big enough, we will probably need some sort of tool like that to help us interact with users and manage the roadmap transparently.

**Comment by 0atman** [comment]
Sounds good, I got excited about it :-)
