### ISSUE TITLE
`now/play!` never finishes

### ISSUE THREAD

**Issue by 0atman** [alda-lang/alda-core#61]
My test script hangs at the end of evaluating:

```clojure
(require '[alda.lisp :refer :all])
(require '[alda.now  :as    now])

(now/play!
  (part "accordion"
    (note (pitch :c) (duration (note-length 8)))
    (note (pitch :d))
    (note (pitch :e :flat))
    (note (pitch :f))
    (note (pitch :g))
    (note (pitch :a :flat))
    (note (pitch :b))
    (octave :up)
    (note (pitch :c))))
```

Do I need to call some kind of shutdown function to finish?

**Comment by daveyarwood** [comment]
Hmm, I'm not able to reproduce the issue with the latest versions of alda/core and alda/sound-engine-clj. I started a REPL with those dependencies like this:

```
boot -d alda/core -d alda/sound-engine-clj repl
```

And then pasted in the code above line by line, and I heard the accordion notes.

(Perhaps it's worth noting that the first time you run `now/play!`, you'll see some JSyn logging output and it will block for a few seconds as it initializes the MIDI Synthesizer.)

`now/play!` actually gives you asynchronous playback by default, so when you call it in a REPL, it returns the Clojure map representation of the score immediately.

To interrupt playback, you can call the function that is the value of the `:stop!` key in the map. A quick & easy way to do that in a REPL session is`((:stop! *1))`

**Comment by daveyarwood** [comment]
I wonder if this might be something environment-specific?

**Comment by 0atman** [comment]
I was trying it inside a `lein run`, so very different to how you're running it!

**Comment by daveyarwood** [comment]
Very different indeed :)

I don't know much about how `lein run` works, but I wonder if maybe you
need to explicitly exit by calling `(System/exit 0)`? That would be
something to try. If that works, then I know a couple ways you could make
the script exit only after the score is done playing.

**Comment by daveyarwood** [comment]
Hi @0atman, are you still having issues with this?

**Comment by 0atman** [comment]
Trying now, I can't remember how I was running it. "trying it inside of `lein run`" doesn't sound like a real thing :laughing:

**Comment by 0atman** [comment]
well, that snippet works in the alda repl...

**Comment by 0atman** [comment]
shrug

**Comment by 0atman** [comment]
A little nuance: I left the server running after this test, came back after lunch and java was using 100% of my CPU, with a loadaverage of 7!
