### ISSUE TITLE
Chord slash (/) can't appear at the beginning of sequence if there's no repeat variation

### ISSUE THREAD

**Issue by UlyssesZh** [alda-lang/alda-core#76]
Sometimes I need to make the chord slash at the beginning of a sequence with a repetition variation:
```
(tempo! 96)
piano:
[
	> e16 d+ | e d+ e < b > d c |
	< a8/ << a16 > e a > c e a | b8/ << e16 > e g+
	[> e g+ b | > c8/ <<< a16 > e a > e]'1,3
	[> d > c < b | a8]'2,4 [/ << a16 > e a > r]'2 r4'4
] * 4
```
or a shorter example:
```
piano: [c [/e]'1]*1
```
However, if there is not a repetition variation, you can't use this feature:
```
piano: c [/e] # ERROR
```
Maybe it's a bug.

**Comment by daveyarwood** [comment]
Hi @UlyssesZh,

A chord slash is not intended to be an "event" to be included an in event sequence. If it works now, it's purely by accident! Events include notes, chords, and attribute changes (including octave changes).

For example, if you want to have an event sequence that is repeated 2 times, and on the first time, you want the note `c` and on the second time, you want the chord `c/e`:

```alda
# not guaranteed to work, because a slash is not an event
piano: [c [/e]'2]*2

# works, because a note and a chord are both events
piano: [c'1 [c/e]'2]*2
```

**Comment by daveyarwood** [comment]
Closing this since it's been a while. Let me know if you have any further questions!
