### ISSUE TITLE
V0 and V2 together is different from V1 and V2 together

### ISSUE THREAD

**Issue by UlyssesZh** [alda-lang/alda-core#84]
Why are the two different?
```
piano: [V0: c d %mm e f V2: @mm b]*2
```
```
piano: [V1: c d %mm e f V2: @mm b]*2
```
Maybe it's a bug.

**Comment by elydpg** [comment]
An intended feature. From [The Docs](https://www.github.com/alda-lang/alda/tree/master/doc%2Fvoices.md):

> `V0:` signals the end of a voice grouping and a return to using a single voice -- the first note placed after `V0:` will happen after all voices in the group have finished.
