### ISSUE TITLE
OSC / MIDI OUT / VST / Samples support

### ISSUE THREAD

**Issue by ostov-larion** [alda-lang/alda-core#90]
Add the ability to use external synthesizers for electronic music composition.

It is enough to add the ability to communicate via MIDI Ports. This will allow external VST Hosts and samplers to be used.

**Comment by daveyarwood** [comment]
Hi @ostov-larion , thanks for the issue!

This would be an amazing feature, and I'm definitely on board with adding it myself at some point in the distant future, unless somebody else contributes it sooner :) 

There has been some discussion of this very idea already at https://github.com/alda-lang/alda-sound-engine-clj/issues/7, so I'm closing this one as a duplicate just  to keep things tidy.
